server:
  port: 8002
  domain: ${SERVER_DOMAIN:https://k10a709.p.ssafy.io.com}
  servlet:
    contextPath: "/api/game-service"
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  count: 4
spring:
  application:
    name: game-service
  devtools:
    livereload:
      enabled: true
  kafka:
    bootstrap-servers: k10a709.p.ssafy.io:19092
  elasticsearch:
    uris: http://k10a709.p.ssafy.io:9200
  # redis 추가 설정
#  data:
#    redis:
#      host: redis-master.redis.svc.cluster.local
#      port: 6379
#      password: pass
#logging
logging:
  level:
    org:
      springframework:
        messaging: INFO
        web:
          socket: INFO
      hibernate.orm.jdbc.bind: TRACE
    com.s10p31a709.game.common.aop: INFO

game:
  time:
    waiting: 3
    hide: 30
    seek: 120
    result: 10
  maxCapacity: 12
  object:
    maxSeekerIdx: 14
    maxHiderIdx: 101
  map:
    richRoom:
      startPoint:
        x: -43.8823
        y: 0.03
        z: -27.9526
  fps: 30
